<?php
 define('LANG_CODE', 'vi-VN');
 define('OS_NAME', 'Kết quả xổ số hôm nay');
 define('OS_HOTLINE', '0123456789');
 define('OS_PHONE', '0987654321');
 define('OS_EMAIL', 'trogiup@cclvapp.com');
 define('OS_ADDRESS', '');
 define('OS_FACEBOOK', 'https://fb.com/cclvapp');
 define('OS_YOUTUBE', 'https://youtube.com@cclvapp');
 define('OS_TIKTOK', 'https://tiktok.com/@cclvapp');
 define('OS_INSTAGRAM', '');
 define('OS_LINKEDIN', '');
 define('OS_TWITTER', '');
 define('OS_TELEGRAM', '');
 define('OS_TUMBLR', '');
 define('OS_ZALO', 'https://zalo.vn/+0987654321');
 define('OS_ZALO_OA', '');
 define('OS_TIKTOK_VIDEO', '');
 define('OS_OWNER', 'CCLVAPP');
 define('OS_MAP', '');
 define('OS_LANG', 'VN');
 define('OS_UNIT_CURRENCY', 'Triệu');
 define('OS_TIMEZONE', 'Asia/Ho_Chi_Minh');
 define('OS_SEO', 'Kết quả xổ số hôm nay');
 define('OS_SUBSEO', 'CCLVAPP');
 define('URL_FOOT_OS', '.html');
 define('URL_GPT_API', '');
 define('ADMIN_CAPTCHA', false); 